### ISSUE TITLE
Trezor model T halts signing if >100 inputs

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/BTCPayServer.Vault#77]
Forwarded for a Telegram user:
----
So after extensive testing:

The issue with the trezor model T latest firmware (2.6.3)

If the Tx input is higher than 100 or so,  it will halt  the signtx part . So btcpay server vault shows signTx and few sec after it just stops , and nothing ever shows on the trezor. (Again this doesn't happen with small tx input). 

I've confirmed this with 4 computers (windows 10) and 2 trezor model T.

Elecrum doesn't have this issue (for your reference).

This is a real issue, not only affecting me so it's with being posted to support the BTcpay eco system.

I have tried version 2.05 up to 2.08 . All same issue

**Comment by ndeet** [comment]
Seems this is likely an HWI issue as it also happens with Sparrow wallet.

**Comment by divinationstar** [comment]
I have the same issue with Ledger Nano X but with over 150 inputs. I posted this issue under "Vault not working right on linux"  #74.

**Comment by NicolasDorier** [comment]
I confirm. A workaround is selecting less inputs. It seems, at least on windows, that having too long parameters is problematic. I'm not sure how to fix this at this point.

**Comment by NicolasDorier** [comment]
The issue I have is maybe not the same as @divinationstar

**Comment by NicolasDorier** [comment]
Closing this one as the original issue is about windows bug, which I just fixed on https://github.com/btcpayserver/BTCPayServer.Vault/releases/tag/Vault%2Fv2.0.9

**Comment by NicolasDorier** [comment]
https://github.com/btcpayserver/BTCPayServer.Vault/issues/74#issuecomment-1905197894

**Comment by NicolasDorier** [comment]
@ndeet @divinationstar please check on windows if you still have the same bug.

The symptom you should see now is the Trezor T signing while the `signtx` on Vault disappear. If that is the case, this is probably a bug of HWI. Bug please open another issue, as the previous issues got polluted with other problems.

**Comment by AlphaTEsterUnited** [comment]
Dear guys, the issue is not resolved. See: https://github.com/bitcoin-core/HWI/issues/720#issuecomment-1910678759

Thanks :)

**Comment by lucho5844** [comment]
No admitimos ese tipo de archivo vuelve  a intentarlo  con Gif,  JPEGCTC.
